<a href="https://colab.research.google.com/github/NeelDelivala/21CSS101J-RA2211042010004-Python/blob/main/Descriptive_Stats.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Descriptive Statistics in NumPy


Descriptive statistics describe the basic and important features of data.

Descriptive statisticshelp simplify and summarize large amounts of data in a sensible manner. 

For instance, consider the Cumulative Grade Point Index (CGPI), which is used to describe the general performance of a student across a wide range of course experiences.

Descriptive statistics involve evaluating measures of center(centrality measures) and measures of dispersion(spread).

# Centrality measures

Centrality measures give us an estimate of the center of a distribution. It gives us a sense of a typical value we would expect to see. 
The three major measures of center include the 


*   Mean
*   Median
*   Mode

## Mean
The average of the given values. 

To compute mean, sum all the values and divide the sumby the number of values.

Mean= ∑(x)/n

∑(x) --> Sum of values of observation

n --> Count of observation

**uses:** to find average sales per day

In [ ]:
import numpy as np
A = np.array([10,14,11,7,9.5,15,19])
print(A)
b=np.mean(A)
print("Mean:",b)

[10.  14.  11.   7.   9.5 15.  19. ]
Mean: 12.214285714285714


## Median
Middle most value of the observation

To calculate the median, arrange the data points in the increasing order and the middle value is the median. 

It is easy to find out the middle value if there is anodd number of data points, say, we want to find the median for marks of all students forSubject 1.

When marks are arranged in the increasing order, we get {7,9.5,10,11,14,15,19}. Clearly, the middle value is 11; therefore, the median is 11.

numpy.median(a, axis=None)

a: array containing numbers whose median is required
axis: axis or axes(Row-0/Column-1) along which the median is computed, 

**uses:** to select the medium risk involvement options

In [ ]:
import numpy as np
A = np.array([7,9.5,10,11,14,15,19])
print(A)
b=np.median(A)
print("Mean:",b)

[ 7.   9.5 10.  11.  14.  15.  19. ]
Mean: 11.0


In [ ]:
B=np.array([[2,3,4],[3,4,5],[6,7,8],[9,10,11]])
print(B)
c=np.median(B,axis=1)
print(c)

[[ 2  3  4]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 3.  4.  7. 10.]


## Mode
Highest frequency of the particular value among observation.

The value that occurs the most number of times in our data set. 

stats.mstats.mode(a, axis=0)

a: array containing numbers whose mode is required
axis: axis or axes along which the mode is computed, default is to compute the mode of the flattened array

Mode= 3(median)-2(mean)

***Uses:*** To find the rating given by the maximum number of user.

In [ ]:
import numpy as np
from scipy import stats
A = np.array([5,5,1,3,5,4,1,5])
print(A)
b=stats.mode(A,axis=0)
print("Mode:",b)

[5 5 1 3 5 4 1 5]
Mode: ModeResult(mode=array([5]), count=array([4]))


In [ ]:
B=np.array([[1,1,1],[1,4,0],[1,2,1]])
print(B)
c=stats.mode(B,axis=0)
print(c)

[[1 1 1]
 [1 4 0]
 [1 2 1]]
ModeResult(mode=array([[1, 1, 1]]), count=array([[3, 1, 2]]))


# Measures of dispersion
Measures of dispersion are values that describe how the data varies.

It gives us a sense of how much the data tends to diverge from the typical value, while central measures give us an idea about the typical value of the distribution.


*   Range
*   Variance
*   Standard deviation
*   Percentile
*   Min
*   Max


## Range
The difference between the largest and the smallest value in a data set

In [ ]:
import numpy as np
A = np.array([10,14,11,7,9.5,15,19])
print(A)
b=np.ptp(A, axis=0)
print("Range:",b)

[10.  14.  11.   7.   9.5 15.  19. ]
Range: 12.0


## Standard deviation
The square root of the variance.

Standard Deviation S = \begin{array}{l}S=\sqrt{\frac{\sum(X-\bar{X})^{2}}{n-1}}\end{array}



In [ ]:
import numpy as np
A = np.array([25,10,15,12,13])
print(A)
b=np.std(A, axis=0)
print("Standard Deviation:",b)

[25 10 15 12 13]
Standard Deviation: 5.253570214625479


## Variance
The average of the squared differences from the mean. 

The sum of squared deviations from the mean divided by n – 1 where n is the
number of data values.

variance v = \begin{array}{l}S={\frac{\sum(X-\bar{X})^{2}}{n-1}}\end{array}

In [ ]:
import numpy as np
A = np.array([46,69,32,60,52,41])
print(A)
b=np.var(A)
print("Variance:",b)

[46 69 32 60 52 41]
Variance: 147.66666666666666


## Percentile
The value such that P percent of the data lies below.

A measure which indicates the value below which a given percentage of points in a dataset fall.

In [ ]:
import numpy as np
A = np.array([46,69,32,60,52,41])
print(A)
b=np.percentile(A,25)
print("Percentile:",b)

[46 69 32 60 52 41]
Percentile: 42.25


In [ ]:
import numpy as np
A = np.array([46,69,32,60,52,41])
print(A)
b=np.quantile(A,0.5)
print("Quantile:",b)

[46 69 32 60 52 41]
Quantile: 49.0


## Min and Max
Finding minimum value in the array
Finding Maximum value in the array

In [ ]:
import numpy as np
A = np.array([46,69,32,60,52,41])
print(A)
b=np.max(A)
d=np.min(A)
print("MAX:",b)
print("MIN:",d)

[46 69 32 60 52 41]
MAX: 69
MIN: 32
