<a href="https://colab.research.google.com/github/NeelDelivala/21CSS101J-RA2211042010004-Python/blob/main/RA2211042010004.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello World!")

Hello World!


In [ ]:
print("Hello")
#comment
print("World")

Hello
World


In [ ]:
a="Hello"
a=a+"World"
print(a)

HelloWorld


In [ ]:
x="Hello"
y="World"
print(x,y)

Hello World


In [ ]:
x="Hello"
y="World"
print(x+y)

HelloWorld


In [ ]:
a=5
b=9.0
c="String"
print(type(a))
print(type(b))
print(type(c))

<class 'int'>
<class 'float'>
<class 'str'>


In [ ]:
x=12E4
print(x)

120000.0


In [ ]:
x=12+9j
print(type(x))

<class 'complex'>


In [ ]:
x=int(1)
y=int(3.9)
z=int("7")
print(x)
print(y)
print(z)

1
3
7


In [ ]:
x=float(1)
y=float(9.89)
z=float("4")
print(x)
print(y)
print(z)

1.0
9.89
4.0


In [ ]:
x="Google Colab Python"
print(x[0])

G


In [ ]:
x="Google Colab Python"
print(x[0:6])

Google


In [ ]:
x="StackOverflow"
print(len(x))
print(x.lower())
print(x.upper())


13
stackoverflow
STACKOVERFLOW


In [ ]:
x="StackOverflow"
print(x.replace("S","G"))

GtackOverflow


In [ ]:
x=8
y=2
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x%y)


10
6
16
4.0
0


In [ ]:
mylist=["C","C++","Python"]
print(mylist)

['C', 'C++', 'Python']


In [ ]:
mylist=["C","C++","Python"]
print(mylist[1])

C++


In [ ]:
mylist=["C","C++","Python"]
mylist[1]="Cython"
print(mylist[1])

Cython


In [ ]:
mylist=["C","C++","Python"]
for x in mylist:
    print(x)

C
C++
Python


In [ ]:
mylist=["C","C++","Python"]
if "C" in mylist:
  print("'C' is in my Programming language list")

'C' is in my Programming language list


In [ ]:
mylist=["C","C++","Python"]
print(len(mylist))

3


In [ ]:
mylist=["C","C++","Python"]
mylist.append("Cython")
print(mylist)

['C', 'C++', 'Python', 'Cython']


In [ ]:
mylist=["C","C++","Python"]
mylist.insert(1,"SQL")
print(mylist)

['C', 'SQL', 'C++', 'Python']


In [ ]:
mylist=["C","C++","Python"]
mylist.remove("C++")
print(mylist)

['C', 'Python']


In [ ]:
mylist=["C","C++","Python"]
del mylist[2]
print(mylist)

['C', 'C++']


In [ ]:
mylist=["C","C++","Python"]
mylist.clear()
print(mylist)

[]


In [ ]:
mylist=list(("C","C++","Python"))
print(mylist)

['C', 'C++', 'Python']


In [ ]:
mytuple=("Apple","Banana","Crane")
#Tuple is similar to list
print(mytuple)

('Apple', 'Banana', 'Crane')


In [ ]:
myset={"Car","Bike","Boat"}
print(myset)
#Set print order is random

{'Car', 'Boat', 'Bike'}


In [ ]:
myset={"Car","Bike","Boat"}
print("Bike" in myset)

True


In [ ]:
myset={"Car","Bike","Boat"}
myset.update(["Plane","Bicycle","Auto"])
print(myset)

{'Auto', 'Plane', 'Car', 'Boat', 'Bicycle', 'Bike'}


In [ ]:
myset={"Car","Bike","Boat"}
myset.discard("Bike")
print(myset)

{'Car', 'Boat'}


In [ ]:
myset={"Car","Bike","Boat"}
x=myset.pop()
#pop removes last item in a set
print(x)
print(myset)

Car
{'Boat', 'Bike'}


In [ ]:
myset={"Car","Bike","Boat"}
del myset
#Will raise error as set is deleted
print(myset)

NameError: ignored

In [ ]:
myset=set(("Car","Bike","Plane"))
print(myset)

{'Plane', 'Car', 'Bike'}


In [ ]:
mydict = {
    "Brand":"Ferrari",
    "Model":"FXX991",
    "Year":"2020",
}
print(mydict)

{'Brand': 'Ferrari', 'Model': 'FXX991', 'Year': '2020'}


In [ ]:
mydict = {
    "Brand":"Ferrari",
    "Model":"FXX991",
    "Year":"2020",
}
x=mydict["Brand"]
print(x)

Ferrari


In [ ]:
mydict = {
    "Brand":"Ferrari",
    "Model":"FXX991",
    "Year":"2020",
}
mydict["Model"]="SX991"
print(mydict)

{'Brand': 'Ferrari', 'Model': 'SX991', 'Year': '2020'}


In [ ]:
class Person:
  def __init__(self, fname):
    self.firstname = fname

  def printname(self):
    print(self.firstname)

class Student(Person):
  pass

x = Student("Mike")
x.printname()

Mike


In [2]:
import numpy as np
data1=[6,7.5,8,0,1]
arr1=np.array(data1)
print(arr1)
print(arr1.dtype)
print(arr1.shape)
print(arr1.ndim)

[6.  7.5 8.  0.  1. ]
float64
(5,)
1


In [8]:
data2=[[1,2,3,4],[5,5,6,7]]
arr2=np.array(data2)
print(arr2)
print(arr2.ndim)
print(arr2.shape)
print(type(arr2.ndim))
print(type(arr2.shape))
print(arr2[1])

[[1 2 3 4]
 [5 5 6 7]]
2
(2, 4)
<class 'int'>
<class 'tuple'>
[5 5 6 7]


In [12]:
arr=np.array([3.7,-1.2,-2.6])
print(arr)
print(arr.astype(np.int32))


[ 3.7 -1.2 -2.6]
[ 3 -1 -2]


In [16]:
ns=np.array(['1.2','-9.6','42'])
print(ns)
print(ns.astype(float))


['1.2' '-9.6' '42']
[ 1.2 -9.6 42. ]


In [18]:
arr=[20,2,7,1,34]
print("arr:",arr)
print("50th percentile of arr",np.percentile(arr,50))
print("75th percentile of arr",np.percentile(arr,75))

arr: [20, 2, 7, 1, 34]
50th percentile of arr 7.0
75th percentile of arr 20.0


In [22]:
arr=[20,2,7,1,34]
print(np.var(arr))

158.16


In [3]:
import pandas as pd
mydataset={
    'cars':["BMW","Volvo","Ford"],
    'passings':[3,7,2]
}
myvar=pd.DataFrame(mydataset)
print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2


In [5]:
a=[1,7,2]
myvar=pd.Series(a)
print(myvar)
print(myvar[0])

0    1
1    7
2    2
dtype: int64
1


In [8]:
a=[1,7,2]
myvar=pd.Series(a,index=["x","y","z"])
print(myvar)
my=pd.DataFrame(a,index=["x","y","z"])
print(my)

x    1
y    7
z    2
dtype: int64
   0
x  1
y  7
z  2


In [11]:
calories={"day1":420,"day2":380,"day3":390}
myvar=pd.Series(calories,index=["day1","day2"])
print(myvar)

day1    420
day2    380
dtype: int64


In [14]:
data={
    "calories":[420,380,390],
    "duration":[50,40,45]
}
myvar=pd.DataFrame(data)
print(myvar)

   calories  duration
0       420        50
1       380        40
2       390        45


In [18]:
data={
    "calories":[420,380,390],
    "duration":[50,40,45]
}
myvar=pd.DataFrame(data)
print(myvar)
print(myvar.loc[0])
print(myvar.loc[[0, 1]])

   calories  duration
0       420        50
1       380        40
2       390        45
calories    420
duration     50
Name: 0, dtype: int64
   calories  duration
0       420        50
1       380        40


In [19]:
data={
    "calories":[420,380,390],
    "duration":[50,40,45]
}
myvar=pd.DataFrame(data,index=["day1","day2","day3"])
print(myvar)

      calories  duration
day1       420        50
day2       380        40
day3       390        45


In [20]:
data={
    "calories":[420,380,390],
    "duration":[50,40,45]
}
myvar=pd.DataFrame(data,index=["day1","day2","day3"])
print(myvar)
print(myvar.loc["day2"])

      calories  duration
day1       420        50
day2       380        40
day3       390        45
calories    380
duration     40
Name: day2, dtype: int64


In [27]:
df=pd.read_csv('california_housing_data.csv')
print(df)

FileNotFoundError: ignored

In [29]:
lst=['Geeks','For','Geeks','is','portal','for','Geeks']
df=pd.DataFrame(lst)
print(df)

        0
0   Geeks
1     For
2   Geeks
3      is
4  portal
5     for
6   Geeks


In [38]:
data={'Name':['Jai','Princi','Gaurav','Anuj'],'Age':[27,24,22,32],'Address':['Delhi','Kanpur','Allahbad','Kannauj'],'Qualification':['MSc','MA','MCA','Phd']}
df=pd.DataFrame(data)
print(df)
print("______________________________________")
print(df[['Name','Qualification']])
first=df.loc[0]
second=df.loc[3]
print("\n\n\n",first,"\n\n\n",second)

     Name  Age   Address Qualification
0     Jai   27     Delhi           MSc
1  Princi   24    Kanpur            MA
2  Gaurav   22  Allahbad           MCA
3    Anuj   32   Kannauj           Phd
______________________________________
     Name Qualification
0     Jai           MSc
1  Princi            MA
2  Gaurav           MCA
3    Anuj           Phd



 Name               Jai
Age                 27
Address          Delhi
Qualification      MSc
Name: 0, dtype: object 


 Name                Anuj
Age                   32
Address          Kannauj
Qualification        Phd
Name: 3, dtype: object
